### ISSUE TITLE
General => Setting page toggle not working

### ISSUE THREAD

**Issue by pshakman** [logchimp/logchimp#821] opened 2023-03-01 21:05 UTC
When you click on "Allow Signups" then save, it will not save. It stays off that toggle.

Thank you.

<img width="1895" alt="Snag_1e4064a2" src="https://user-images.githubusercontent.com/45835612/222264765-09524da6-5b8c-4fef-9a96-e91bfa8fa17d.png">

**Comment by mittalyashu** [comment] 2023-06-17 09:22
I am not able to reproduce the issue.


https://github.com/logchimp/logchimp/assets/29014463/f8af5b58-79d8-4113-9ec2-f755aae1c6db

May I know which version of LogChimp you're using?

**Comment by mittalyashu** [comment] 2023-12-26 17:12
I'm closing this issue for now, please do not hesitate to reopen this issue again.

**Closed by mittalyashu** 2023-12-26 17:12 UTC
Labels: bug, wait for response

**Comment by Ja4V8s28Ck** [comment] 2025-08-17 11:06
I tried to reproduce this issue with the latest `logchimp` and the UI toggle works perfectly without any issue. If anyone is having the same error in the future, please make sure to link a video of the issue.
