### ISSUE TITLE
render deploys are broken

### ISSUE THREAD

**Issue by phishy** [logchimp/logchimp#598] opened 2021-11-19 20:54 UTC
**Describe the bug**
Clicking the Deploy to render button throw errors about the node engine version and fails

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Getting Started'.. 'Installation'
2. Click on Render one click deploy
3. Fails to install

**Expected behaviour**
Should install without error

**Screenshots**

**Desktop (please complete the following information):**
 - LogChimp [e.g. v0.2.0]
 - Browser version [e.g. v22]

**Additional context**

**Comment by mittalyashu** [comment] 2021-11-20 05:17
Hello @phishy,

Thank you using LogChimp. I'll look into this issue. 🙂

**Comment by mittalyashu** [comment] 2021-11-20 16:46
This issue has been resolved in https://github.com/logchimp/deploy-buttons/commit/ccc7bccaa1784687476402177d68cb068584454c

You can also check the updated docs at https://logchimp.codecarrot.net/docs/install/render

**Comment by mittalyashu** [comment] 2021-11-20 16:48
@phishy I'm closing this issue for now, please don't hesitate to re-open this issue in case you're facing similar issue again.

**Comment by phishy** [comment] 2021-11-20 16:49
Thanks!

**Closed by mittalyashu** 2021-11-20 16:48 UTC
Labels: bug, wait for review

**Comment by mittalyashu** [comment] 2021-11-20 16:56
Duplicate of https://github.com/logchimp/deploy-buttons/issues/1
